########################################
########################################
##
##  Copyright (C) 2014 Korovasoft, Inc.
##
##  File:
##      \file .travis.yml
##
##  Description:
##      \brief Travis-CI configuration file
##
##  Author:
##      \author J. Caleb Wherry
##
########################################
########################################

language: 
  - cpp

compiler:
  - gcc
#  - clang

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update

install:
  - sudo apt-get --no-install-recommends install doxygen libgtest-dev
  - sh -c 'echo "Before install: ${CXX}"'
  - if [ "${CXX}" = "g++" ]; then sudo apt-get install g++-4.8; fi
  - sh -c 'echo "After install: ${CXX}"'

before_script:
  - cd /usr/src/gtest; sudo cmake CMakeLists.txt; sudo make; sudo cp *.a /usr/lib; cd -
  - if [ "${CXX}" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
  - sh -c 'echo "Before script: ${CXX}"'

script:
  - "./qa/build.sh"

notifications:
  recipients:
    - calebwherry@gmail.com
    - robertofrances@gmail.com
  email:
    on_success: change
    on_failure: always
