########################################
########################################
##
##  Copyright (C) 2014 Korovasoft, Inc.
##
##  File:
##      \file .travis.yml
##
##  Description:
##      \brief Travis-CI configuration file
##
##  Author:
##      \author J. Caleb Wherry
##
########################################
########################################

language: 
  - cpp

compiler:
  - gcc
  - clang

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update

install:

  # Install newest GNU gcc compiler:
  - if [ "${CXX}" = "g++" ]; then sudo apt-get install g++-4.8; fi
  - if [ "${CXX}" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

  # Install GoogleTest testing framework:
  - sudo apt-get install libgtest-dev python3

  # Install doxygen without all those lame depends like latex:
  - sudo apt-get --no-install-recommends install doxygen

  # Install new(er) cmake with some crazy magic I found online:
  - sudo apt-get install devscripts
  - dget -x -u http://archive.ubuntu.com/ubuntu/pool/main/c/cmake/cmake_2.8.9-0ubuntu1.dsc
  - sudo apt-get build-dep cmake
  - cd cmake* && fakeroot dpkg-buildpackage
  - sudo dpkg -i ../cmake*deb

before_script:

  # Correctly install GoogleTest static libraries:
  - cd /usr/src/gtest; sudo cmake CMakeLists.txt; sudo make; sudo cp *.a /usr/lib; cd -

script:
  - "./build.py"

notifications:
  recipients:
    - calebwherry@gmail.com
    - robertofrances@gmail.com
  email:
    on_success: change
    on_failure: always
