########################################
########################################
##
##  Copyright (C) 2014 Korovasoft, Inc.
##
##  File:
##      \file .travis.yml
##
##  Description:
##      \brief Travis-CI configuration file
##
##  Author:
##      \author J. Caleb Wherry
##
########################################
########################################

language: 
  - cpp

compiler:
  - gcc
#  - clang

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update

install:
  - sudo apt-get install libgtest-dev
  - sudo apt-get --no-install-recommends install doxygen
  - if [ "${CXX}" = "g++" ]; then sudo apt-get install g++-4.8; fi

  # Newest cmake version:
  - wget http://www.cmake.org/files/v2.8/cmake-2.8.12.2.tar.gz
  - tar -xzvf cmake-2.8.11.tar.gz
  - cd cmake-2.8.11
  - ./bootstrap --prefix=/usr --system-libs --mandir=/share/man --docdir=/share/doc/cmake-2.8.11
  - make
  - make test
  - sudo make install
  - cd -

before_script:
  - if [ "${CXX}" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
  - cd /usr/src/gtest; sudo cmake CMakeLists.txt; sudo make; sudo cp *.a /usr/lib; cd -

script:
  - "./qa/build.sh"

notifications:
  recipients:
    - calebwherry@gmail.com
    - robertofrances@gmail.com
  email:
    on_success: change
    on_failure: always
