########################################
########################################
##
##  Copyright (C) 2014 Korovasoft, Inc.
##
##  File:
##      \file .travis.yml
##
##  Description:
##      \brief Travis-CI configuration file
##
##  Author:
##      \author J. Caleb Wherry
##
########################################
########################################

python:
  - "3.2"

language: 
  - cpp

compiler:
  - gcc
#  - clang

before_install:

  # Repo update for g++4.8:
  - if [ "${CXX}" = "g++" ]; then 
      sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y;
    fi

  # Repo update for clang++3.4:
  - if [ "${CXX}" = "clang++" ]; then 
      sudo add-apt-repository -y ppa:h-rayflood/llvm;
    fi

  # Update repo:
  - sudo apt-get update

install:

  # Install newest GNU gcc compiler:
  - if [ "${CXX}" = "g++" ]; then 
      sudo apt-get install g++-4.8;
      export CXX="g++-4.8" CC="gcc-4.8"; 
    fi

  # Install newest clang compiler:
  # TODO: All this work and it still doesn't work right... Giving up for now...
  - if [ "${CXX}" = "clang++" ]; then
      sudo apt-get install --allow-unauthenticated clang-3.4;
      svn co http://llvm.org/svn/llvm-project/libcxx/trunk libcxx;
      cd libcxx/lib && bash buildit;
      sudo cp ./libc++.so.1.0 /usr/lib/;
      sudo mkdir /usr/include/c++/v1;
      cd .. && sudo cp -r include/* /usr/include/c++/v1/;
      cd /usr/lib && sudo ln -sf libc++.so.1.0 libc++.so;
      sudo ln -sf libc++.so.1.0 libc++.so.1 && cd $cwd;
      rm -rf libcxx;
      export CXX="clang++-3.4" CC="clang-3.4";
    fi

  # Install GoogleTest testing framework:
  - sudo apt-get install libgtest-dev libcr-dev mpich2 mpich2-doc

  # Install doxygen without all those lame depends that are HUGE (<cough> LATEX):
  - sudo apt-get --no-install-recommends install doxygen

  # Install python modules:
  - sudo pip install colorama

before_script:

  # Correctly install GoogleTest static libraries:
  - cd /usr/src/gtest; sudo cmake CMakeLists.txt; sudo make; sudo cp *.a /usr/lib; cd -

script:
  - "./build.py"

notifications:
  recipients:
    - calebwherry@gmail.com
    - robertofrances@gmail.com
  email:
    on_success: always
    on_failure: always
