########################################
########################################
##
##  Copyright (C) 2014 Korovasoft, Inc.
##
##  File:
##      \file .travis.yml
##
##  Description:
##      \brief Travis-CI configuration file
##
##  Author:
##      \author J. Caleb Wherry
##
########################################
########################################

language: 
  - cpp

compiler:
  - gcc
#  - clang

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update

install:

  # Install newest GNU gcc compiler:
  - if [ "${CXX}" = "g++" ]; then sudo apt-get install g++-4.8; fi
  - if [ "${CXX}" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

  # Install GoogleTest testing framework:
  - sudo apt-get install libgtest-dev python3 python-pip

  # Install doxygen without all those lame depends like latex:
  - sudo apt-get --no-install-recommends install doxygen

  # Install python modules:
  - sudo pip install colorama

before_script:

  # Correctly install GoogleTest static libraries:
  - cd /usr/src/gtest; sudo cmake CMakeLists.txt; sudo make; sudo cp *.a /usr/lib; cd -

  # Put colorama package in correct place:
  - sudo mkdir /usr/local/lib/python3.2/dist-packages/colorama/
  - sudo cp /usr/local/lib/python2.7/dist-packages/colorama/* /usr/local/lib/python3.2/dist-packages/colorama/

script:
  - "./build.py"

notifications:
  recipients:
    - calebwherry@gmail.com
    - robertofrances@gmail.com
  email:
    on_success: always
    on_failure: always
