########################################
########################################
##
##  Copyright (C) 2014 Korovasoft, Inc.
##
##  File:
##      \file .travis.yml
##
##  Description:
##      \brief Travis-CI configuration file
##
##  Author:
##      \author J. Caleb Wherry
##
########################################
########################################

language: 
  - cpp

compiler:
  - gcc
  - clang

before_install:

  # Repo updates for g++4.8:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y;

  # Repo updates for clang++-3.2:
  - sudo add-apt-repository -y ppa:h-rayflood/llvm;

  # Update repo:
  - sudo apt-get update;

install:

  # Install newest GNU gcc compiler:
  - if [ "${CXX}" = "g++" ]; then 
      sudo apt-get install g++-4.8;
      export CXX="g++-4.8" CC="gcc-4.8"; 
    fi

  # Install newest clang compiler:
  # TODO: All this work and it still doesn't work right... Giving up for now...
  - if [ "${CXX}" = "clang++" ]; then
      sudo apt-get install libstdc++-4.8-dev clang-3.4;
      export CXX="clang++-3.4" CC="clang-3.4";
    fi

  # Main apt-get installs:
  - sudo apt-get install libgtest-dev python3 python-pip libcr-dev mpich2 mpich2-doc

  # Install doxygen without all those lame depends that are HUGE (<cough> LATEX):
  - sudo apt-get --no-install-recommends install doxygen

  # Install python modules:
  - sudo pip install colorama

before_script:

  # Correctly install GoogleTest static libraries:
  - cd /usr/src/gtest; sudo cmake CMakeLists.txt; sudo make; sudo cp *.a /usr/lib; cd -

  # Put installed colorama package in correct place for new python version. This is extremely sloppy and nasty but 
  #  it is the quickest way I could it to work on Travis:
  - sudo mkdir /usr/local/lib/python3.2/dist-packages/colorama/
  - sudo cp /usr/local/lib/python2.7/dist-packages/colorama/* /usr/local/lib/python3.2/dist-packages/colorama/

script:
  - "./build.py"

notifications:
  recipients:
    - calebwherry@gmail.com
    - robertofrances@gmail.com
  email:
    on_success: always
    on_failure: always
